name: Conditional jobs
on: [push]
jobs:
    current-repo-run:
        if: github.repository == 'sabin-thapa/logo-electronics-nextjs'
        runs-on: ubuntu-latest
        steps:
            - name: echo something
              run: echo ${{github.repository}}
    regular-run:
        runs-on: ubuntu-latest
        steps:
            - name: step 1
              run: echo "NAME=Sabin" >> $GITHUB_ENV
            - name: step 2
              run: echo $NAME