name: Manual trigger

on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Name of the person to greet'
                required: true
                default: 'User'
            purpose:
                description: purpose of the action

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: Greeting person
              run: echo "Buenos dias, ${{github.event.inputs.name}}"