name: Schedule job

on:
  schedule: 
    - cron: '*/2 * * * *'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet user with the current tiem
        run: echo "Hello user, today is ${date}"