name: Schedule job using cron

on:
  schedule: 
    - cron: '*/1 * * * *'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet user with the current tiem
        run: echo "Hello user, today is $(date)"